"""Remove date_of_birth and add age field

Revision ID: da419ff66083
Revises: replace_dob_with_age
Create Date: 2025-04-09 13:21:55.183191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da419ff66083'
down_revision = 'replace_dob_with_age'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_participant')
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.DATE(), nullable=False))
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_participant',
    sa.Column('participant_id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=15), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=15), nullable=False),
    sa.Column('city', sa.VARCHAR(length=15), nullable=True),
    sa.Column('state', sa.VARCHAR(length=15), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('participant_id')
    )
    # ### end Alembic commands ###
